spring.application.name=ciro-backend
server.port=9091

spring.datasource.url=jdbc:postgresql://localhost:5433/ciro_db
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# 'update' crea las tablas automáticamente según las entities definidas
spring.jpa.hibernate.ddl-auto=update 
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
jwt.secret=5556110ddcdddba8b3835331408e4e1b7eb07cc3e3ebc9606edfe43fdfd436f3