package com.ciro.backend.enums;

public enum ReasonForConsultation {
    CIRUGIA_ORTOGNATICA_MAXILOFACIAL,
    IMPLANTOLOGIA,
    ESTETICA_DENTAL,
    BLANQUEAMIENTO,
    PROTESIS,
    ORTODONCIA,
    ODONTOPEDIATRIA_ORTOPEDIA_FUNCIONAL,
    ODONTOLOGIA_GENERAL_RESTAURACION,
    LIMPIEZA_DENTAL_PROFILAXIS,
    REGENERACION_RECONSTRUCCION_OSEA,
    ESTETICA_FACIAL,
    OTRO
}